// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdUSow1d0tpclZ4x05OUrgflViZ8v7fPw',
    appId: '1:334458899561:web:e98b98ecd36f3ebdec66f8',
    messagingSenderId: '334458899561',
    projectId: 'loopcart-61151',
    authDomain: 'loopcart-61151.firebaseapp.com',
    storageBucket: 'loopcart-61151.firebasestorage.app',
    measurementId: 'G-KF24G9KECT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgErR6FYv5AHFgLsCOpzKuigAdxdf5VgI',
    appId: '1:334458899561:android:ccc3ed12895d90d6ec66f8',
    messagingSenderId: '334458899561',
    projectId: 'loopcart-61151',
    storageBucket: 'loopcart-61151.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfSOKN0aCZQ45WQ9YFWiZYomEcBnCY9QY',
    appId: '1:334458899561:ios:254ca4879343ba5eec66f8',
    messagingSenderId: '334458899561',
    projectId: 'loopcart-61151',
    storageBucket: 'loopcart-61151.firebasestorage.app',
    androidClientId: '334458899561-jkaedrc25ic8l1c1v9bb5nfur5muie19.apps.googleusercontent.com',
    iosClientId: '334458899561-1cm7k7kdjard67vq1lm7cl554aug8vjj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfSOKN0aCZQ45WQ9YFWiZYomEcBnCY9QY',
    appId: '1:334458899561:ios:254ca4879343ba5eec66f8',
    messagingSenderId: '334458899561',
    projectId: 'loopcart-61151',
    storageBucket: 'loopcart-61151.firebasestorage.app',
    androidClientId: '334458899561-jkaedrc25ic8l1c1v9bb5nfur5muie19.apps.googleusercontent.com',
    iosClientId: '334458899561-1cm7k7kdjard67vq1lm7cl554aug8vjj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdUSow1d0tpclZ4x05OUrgflViZ8v7fPw',
    appId: '1:334458899561:web:e90ebe386fad2ab1ec66f8',
    messagingSenderId: '334458899561',
    projectId: 'loopcart-61151',
    authDomain: 'loopcart-61151.firebaseapp.com',
    storageBucket: 'loopcart-61151.firebasestorage.app',
    measurementId: 'G-R2BG3BH2WN',
  );
}
